Feature/gender qc
UMCUGenetics/Dx_resources pull request #126
Opened 2023-04-07 06:22 UTC by melferink

* Included gender in CNV QC files

2023-04-18 14:42 UTC, rernst requested changes
Wat opmerkingen en een merge conflict.

2023-04-18 14:42 UTC, rernst commented on ExomeDepth/run_ExomeDepth.py
> +        ):
Spacing

2023-04-18 14:42 UTC, rernst commented on ExomeDepth/run_ExomeDepth.py
> +    stats = (subprocess.getoutput("tail -n1 {}".format(vcf)).split()[-1]).split(":")
Waarom de `(` voor subprocess?

2023-04-18 14:42 UTC, rernst commented on ExomeDepth/run_ExomeDepth.py
> +    stats = (subprocess.getoutput("tail -n1 {}".format(vcf)).split()[-1]).split(":")
Wat gebeurt er als de VCF eindigt met een lege regel? Ik zou het netter vinden als je de vcf gewoon opent in python en op zoek gaat naar de eerste/laatste/n vcf regel.

PyVCF is toch al een requirement.

2023-04-18 14:42 UTC, rernst commented on ExomeDepth/run_ExomeDepth.py
> +    correlation, del_dup_ratio, number_calls = float(stats[4]), float(stats[8]), int(stats[9])
Wat gebeurd er als de volgorde van deze velden veranderd?

2023-04-18 14:42 UTC, rernst commented on ExomeDepth/run_ExomeDepth.py
> +    if args.vcf_filename_suffix:
Samenvoegen met if blok op regel 309

2023-04-19 11:27 UTC, melferink commented on ExomeDepth/run_ExomeDepth.py
> +        ):
What about it? 
Zo beter?

2023-05-30 10:46 UTC, rernst approved these changes

2023-05-31 08:24 UTC, merged