Feature/removeGenderQC
UMCUGenetics/Dx_resources pull request #143
Opened 2023-09-27 09:30 UTC by melferink

* reverted code to previous without Gender in QC summary and parseCNVQC

2023-10-10 12:01 UTC, rernst requested changes

2023-10-10 12:01 UTC, rernst commented on ParseCNVQC/parse_cnv_qc.py
> +                                analysis, "\t".join(splitline[0:333]), CR, PD, TC, CR_passed, PD_passed, TC_passed, QC_failed)
Dit moet gewoon `3` zijn?

2023-10-13 08:39 UTC, melferink commented on ParseCNVQC/parse_cnv_qc.py
> +                                analysis, "\t".join(splitline[0:333]), CR, PD, TC, CR_passed, PD_passed, TC_passed, QC_failed)
Yes...good catch ;)

2023-10-13 10:32 UTC, rernst approved these changes

2023-12-06 14:13 UTC, merged