Refset in qc in log
UMCUGenetics/Dx_resources pull request #57
Opened 2020-11-18 12:19 UTC by melferink

* Added used RefSet in QC log files.
* changed VCF stats criteria in settings.py

2020-11-18 14:15 UTC, rernst requested changes

2020-11-18 14:15 UTC, rernst commented on ExomeDepth/submit_batch_exomedepth.py
> +        os.system("mkdir -p {inputfolder}/QC/CNV/".format(inputfolder=args.inputfolder, today=today))
`today` argument bij `format` gebruik je niet?

2020-11-19 10:16 UTC, melferink commented on ExomeDepth/submit_batch_exomedepth.py
> +        os.system("mkdir -p {inputfolder}/QC/CNV/".format(inputfolder=args.inputfolder, today=today))
Goed punt. Gaat eruit

2020-11-20 09:01 UTC, rernst approved these changes

2020-11-20 09:06 UTC, merged